### ISSUE TITLE
Sometimes hang in when running it for the second time. 

### ISSUE THREAD

**Issue by freefishfun** [tuespetre/TuesPechkin#102]
Issues Description: 

First scenario: Running directly in Visual Studio 2012: First time it just fine. When I run it for the second time(or third time..), about 20% chance it will hang in Convert(document) line. If you run it again and again, the CPU usage will be up to 100%.
Second scenario:When I run it using the javascript openning window function, passing query string to get corresponding htmlstring, most of the time it hangs. If you wait for like 3 minutes then run, it sometimes succeed, but CPU usage will finally be up to 100%.
Third scenario: When I run first time in VS, then change some codes in htmlstring, most of time it hangs. It is much like the second scenario.

I directly download from Nuget: My codes is like:

``` csharp
public static Iconverter converter{get;set;}
....
Protected void Page_Load(object sender, EventArgs e)
{
    HtmlToPdfDocument document = null;
    document = new HtmlDocument
    {
        GlobalSettings=
        {...},
        Objects = { new ObjectSettings {HtmlText = htmlstring()},
    }

    converter =null;
    converter = new StandardConverter(
                           new PdfToolset( 
                               new Win32EmbeddedDeployment( 
                                   new TempFolderDeployment())));
    result = converter.Convert(document);
    converter = null;
    document = null;
    return result;
}

private string htmlstring()
{
    //will return static string in scenario one
    //will return dynamic string in scenario two
   ...
}
```

Thank you.

**Comment by tuespetre** [comment]
Please see the README.md, this section specifically:

https://github.com/tuespetre/TuesPechkin#or-in-an-iis-hosted-application

**Comment by freefishfun** [comment]
Thank you for your reply, Derek.
But I am still a little confused. When you say "do not run it more than
once in the application life cycle", what does it mean? To re-run the
application, I have to close and start Visual Studio? On the server I have
to restart the application in IIS? If this is the case, I'm not able to use
this api.

I am pretty a beginner of this, Thank you for explanation.

**Comment by tuespetre** [comment]
It means that you do not want to create a `new StandardConverter(...)` each time your page loads, it should only be created one time and re-used every request. A static constructor or a `static readonly` field is good for this.

**Comment by freefishfun** [comment]
I tried the followings with application hosted in IIS(32bit):
IConverter converter = new ThreadSafeConverter(new PdfToolset(new
Win32EmbeddedDeployment(new TempFolderDeployment())));

And

IConverter converter = new ThreadSafeConverter(new
RemotingToolset<PdfToolset>(new Win32EmbeddedDeployment(new
TempFolderDeployment())));

Still, they won't run for the second time. The IE keep spinning. I have to
restart application pool and IIS.

Thank you.

**Comment by tuespetre** [comment]
You need the second one you posted, and it **cannot** be in your Page_Load method. To repeat myself: "...you do not want to create a new [converter] each time your page loads..."

**Comment by viklele** [comment]
You should create it in Application_Start in Global.asax or create a singleton (static should effectively achieve that). Make sure that you create a lock around the Convert method call to make it thread safe.
