### ISSUE TITLE
SVG empty space character rendering bug

### ISSUE THREAD

**Issue by alin-prisecaru** [tuespetre/TuesPechkin#109]
I have an issue with the converter when using SVGs.
The details are ok, but when I try to convert an SVG that has empty spaces inside it, I get some weird characters instead of the proper thing.
The text I talk about is:
_[ $                               (including capitalization)]_

The SVG is:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="924.066px" height="45.045px" version="1.1" viewBox="0 0 718 35">
  <defs />
  <g transform="translate(0.75, 0.75)">
    <rect x="105" y="0" width="246" height="34" fill="#ffffff" stroke="#000000" pointer-events="none" />
    <g transform="translate(108,9)">
      <switch>
        <foreignObject pointer-events="all" width="241" height="17" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility">
          <div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; font-size: 12px; font-family: Arial; color: rgb(0, 0, 0); line-height: 1.26; vertical-align: top; overflow: hidden; max-height: 29px; max-width: 241px; width: 240.5px; white-space: normal; text-align: center;" class="undefined"> $                               (including capitalization)<br /></div>
        </foreignObject>
      </switch>
    </g>
    <rect x="25" y="3" width="60" height="30" fill="none" stroke="none" pointer-events="none" />
    <g transform="translate(27,11)">
      <switch>
        <foreignObject pointer-events="all" width="56" height="17" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility">
          <div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; font-size: 12px; font-family: Arial; color: rgb(0, 0, 0); line-height: 1.26; vertical-align: top; overflow: hidden; max-height: 26px; max-width: 56px; width: 56px; white-space: normal; text-align: center;" class="undefined">Text</div>
        </foreignObject>
      </switch>
    </g>
    <g opacity="0.01" transform="translate(-1,1)">
      <switch>
        <foreignObject pointer-events="all" width="1" height="1" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility">
          <div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; font-size: 12px; font-family: Arial; color: rgb(0, 0, 0); line-height: 1.26; vertical-align: top; overflow: hidden; max-height: 0px; max-width: 0px; white-space: nowrap; text-align: center; width: 0px;" class="undefined">.</div>
        </foreignObject>
      </switch>
    </g>
    <g opacity="0.01" transform="translate(715,35)">
      <switch>
        <foreignObject pointer-events="all" width="1" height="1" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility">
          <div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; font-size: 12px; font-family: Arial; color: rgb(0, 0, 0); line-height: 1.26; vertical-align: top; overflow: hidden; max-height: 0px; max-width: 0px; white-space: nowrap; text-align: center; width: 0px;" class="undefined">.</div>
        </foreignObject>
      </switch>
    </g>
  </g>
</svg>`

Here is how it should look (test it by simply placing this code in a html file and open it):
![propersvglook](https://cloud.githubusercontent.com/assets/8037551/7981638/d889b912-0ab8-11e5-9718-35630f9449ee.png)

And here is what I get:
![resultsvginpdf](https://cloud.githubusercontent.com/assets/8037551/7981699/5c403664-0ab9-11e5-8ddf-3b64fcb43048.png)

And the text taken from the pdf:
_[ï¿½$ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½(including capitalization)]_

So every empty space that is not between 2 words was transformed into 'ï¿½'.

The case I've shown here might not be the most precise, but the point is that I need in some situations some multiple empty spaces between words in SVGs.

If there is no fix on your side, can you at least point me in the right direction?

Thanks.

**Comment by KoKuToru** [comment]
Renders correctly here, Windows 8.1 with `wkhtmltopdf`-0.12.1.2 (with patched qt).
Which version of `wkhtmltopdf` are you using ?

Anyways this will be hardly the fault of `TuesPechkin`.. 
You probably want to make a bug report at https://github.com/wkhtmltopdf/wkhtmltopdf
(Don't forget to include your OS/`wkhtmltopdf`-version)

**Comment by alin-prisecaru** [comment]
Here is a sample of my code:

``` C#
private void CreatePdfDocumentFromHtml(string htmlContent, string filePath, PdfDocumentPageSetup pdfDocumentPageSetup = null)
        {
            lock (_locker)
            {
                IConverter converter = new ThreadSafeConverter(new RemotingToolset<PdfToolset>(new Win64EmbeddedDeployment(
                    new StaticDeployment(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wkhtmltopdf"))
                )));
                GlobalSettings settings = new GlobalSettings
                {
                    Margins =
                    {
                        Top = 0.8,
                        Bottom = 0.8,
                        Left = 0.6,
                        Right = 0.6,
                        Unit = Unit.Centimeters
                    },
                    ImageDPI = 200,
                    ImageQuality = 400,
                    DPI = 200
                };                


                if (pdfDocumentPageSetup != null)
                {
                    settings = new GlobalSettings
                    {
                        Margins =
                        {
                            Top = pdfDocumentPageSetup.MarginTop,
                            Bottom = pdfDocumentPageSetup.MarginBottom,
                            Left = pdfDocumentPageSetup.MarginLeft,
                            Right = pdfDocumentPageSetup.MarginRight,
                            Unit = Unit.Centimeters
                        },
                        ImageDPI = 200,
                        ImageQuality = 400,
                        DPI = 200,
                        PaperSize = new PechkinPaperSize(pdfDocumentPageSetup.PageWidth.ToString() + "cm", pdfDocumentPageSetup.PageHeight.ToString() + "cm")
                    };
                }


                HtmlToPdfDocument pdfDocument = new HtmlToPdfDocument
                {
                    GlobalSettings = settings,
                    Objects =
                    {
                        new ObjectSettings
                        { 
                            ProduceLocalLinks = true,
                            ProduceForms = true,
                            HtmlText = htmlContent
                        }                    
                    }                
                };

                byte[] pdfDocumentData = converter.Convert(pdfDocument);
                File.WriteAllBytes(filePath, pdfDocumentData);
            }
        }
```

In _wkhtmltopdf_ folder in my application another folder is created called _0.12.2.1_ and it has a single file inside called _wkhtmltox.dll_.

So, I guess my version would be 0.12.2.1, but I'm not sure.
I used for a long time only the old version of TuesPechkin which was a single DLL and I recently switched to this new format where the dlls are separate for the wrapper and wkhtmltopdf.

My OS is Windows 8.1 as well.

Any ideeas of what I should try next ?

**Comment by KoKuToru** [comment]
How do you generate your `htmlContent` ?
Maybe you have a wrong text-encoding (when you load it from somewhere)...

**Comment by alin-prisecaru** [comment]
Hmm you might be right.
I don't specify any settings like that in my source HTML file.
I generate this HTML from one of my views that simply begin like:

``` HTML
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Page Preview</title>

    <style>
```

What encoding should I use ?

**Comment by KoKuToru** [comment]
No idea it should work correctly. If you use `string` and never loaded from an external resource and/or manually transformed between encodings.

I would try to save the `string` to a file and try generate the pdf.
If the file generates the corrupted pdf, check the file for encoding problems..
If the file generates the correct pdf (but the string isn't), something is very wrong..

Btw. I did test your SVG directly, without any `<!DOCTYPE ..` etc. which could affect this too..
As file and as string both worked.

**Comment by alin-prisecaru** [comment]
I fixed it.
I found this: http://www.w3schools.com/charsets/ref_html_utf8.asp

I edited my html and added in the meta tag the following charset:

``` HTML
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" charset="ISO-8859-1"/>
    <title>Report</title>
```

It works ok now. Although I still don't trust this new implementation with the folders and stuff where the DLL is injected.

It works only the first time after starting the application.
If I try to convert once more, it just gets stuck in the convert process and after a long time, it just times out. :(

**Comment by tuespetre** [comment]
In your sample, a converter would be created with each pass through your code. That code should only get called once, either in a static constructor, a static field initializer, or even as a registered singleton in a DI container if you're into that sort of thing.

**Comment by alin-prisecaru** [comment]
Ok, agreed. I tried using a locker as you saw in my previous comments, but still no luck.
The locker was:

``` C#
private static readonly object _locker = new object();
```

... in my class responsible with converting HTML to PDF.

I've read the documentation and I understood that the code should only run once in the application lifetime. 

So how should I deal with this problem in an IIS application where my Web Api should convert HTML to PDF whenever I want to ?

I tried every possible combination of code samples you provided on the homepage of the project for constructing the converter, even this one: 

``` C#
IConverter converter =
    new StandardConverter(
        new PdfToolset(
            new Win64EmbeddedDeployment(
                new TempFolderDeployment()))); // or new StaticDeployment(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wkhtmltopdf"))
```

I guess I need something like a destroy method for IConverter ...

**Comment by alin-prisecaru** [comment]
Sorry for spamming.

I finally understood.
I placed the IConverter as a static variable in a static separate class at the level of the application.
So it will be initialized only 1 time when the IIS application starts.

My class responsible with converting HTML to PDF will simply use the converter:

``` C#
byte[] pdfDocumentData = TuesPechkinInitializerService.converter.Convert(pdfDocument);
```

... and the converter:

``` C#
public static class TuesPechkinInitializerService
    {
        public static IConverter converter = 
            new ThreadSafeConverter(
                new RemotingToolset<PdfToolset>(
                    new Win64EmbeddedDeployment(
                        new StaticDeployment(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wkhtmltopdf"))
                    )
                )
            );
    }
```

You can close this issue if you want to. Thanks for your help :smiley: 
Great plugin !

**Comment by tuespetre** [comment]
Sorry about the confusion. I have issue #88 open to provide an opaque layer like 1.x used to, which should suffice for most users. It's just a matter of finding the time
