### ISSUE TITLE
Publishing 64 bit in IIS application of example code

### ISSUE THREAD

**Issue by hkazaz** [tuespetre/TuesPechkin#113]
Hello,  

I have download and tried TuesPechkin  solution's "TuesPechkin.TestWebApp"  for 64 bit platform and 64 bit platform target. After applying Win32EmbeddedDeployment -> Win64EmbeddedDeployment source code changes , It Compiles Well. 

But I cannot Publish the project . it says 

1>------ Publish started: Project: TuesPechkin.TestWebApp, Configuration: Debug x64 ------
1>Connecting to C:\inetpub\wwwroot\PechkinMVC...
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Transformed Web.config using C:\projects\TuesPechkin-develop2\TuesPechkin-develop\TuesPechkin.TestWebApp\Web.Debug.config into obj\x64\Debug\TransformWebConfig\transformed\Web.config.
1>Copying all files to temporary location below for package/publish:
1>obj\x64\Debug\AspnetCompileMerge\Source.
1>C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v / -p C:\projects\TuesPechkin-develop2\TuesPechkin-develop\TuesPechkin.TestWebApp\obj\x64\Debug\AspnetCompileMerge\Source -u -c C:\projects\TuesPechkin-develop2\TuesPechkin-develop\TuesPechkin.TestWebApp\obj\x64\Debug\AspnetCompileMerge\TempBuildDir 
1>ASPNETCOMPILER(0,0): Error ASPCONFIG: Could not load file or assembly 'TuesPechkin.TestWebApp' or one of its dependencies. . An attempt was made to load a program with an incorrect format.
1>
========== Build: 0 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by tuespetre** [comment]
I might be able to spot something if you commit your changes, push them up to your clone, and provide a link here.

**Comment by hkazaz** [comment]
Hi Derek,
After I installed 64 bit c++ runtime  , I managed to run, Thanks. That is the very important detail I missed.  

```
 On Friday, July 17, 2015 5:50 AM, Derek <notifications@github.com> wrote:
```

 I might be able to spot something if you commit your changes, push them up to your clone, and provide a link here.—

**Comment by tuespetre** [comment]
Ahh. Thanks for the update
