### ISSUE TITLE
Create Signed package of Tues.Pechkin for NuGet.

### ISSUE THREAD

**Issue by pablot** [tuespetre/TuesPechkin#114]
Is this possible for maintainer?

I got a problem with: Assembly generation failed -- Referenced assembly 'TuesPechkin' does not have a strong name.

Thank's.

**Comment by tuespetre** [comment]
I do not plan on adding a strong named version to this repository; sorry. You are free however to build your own copy with a strong name if you require.

**Comment by Dash** [comment]
If anybody else stumbles upon this issue, I thought I'd note down steps I've had to take to build this with signing with Azure Devops Server (TFS).

1. Setup a build against the master git repository
2. Use a "Download secure file" step up front to drop a *.snk of your creation file into the build dir, and name the output something like "keyFile"
3. Add MSBuild arguments:   `/p:SignAssembly=true /p:AssemblyOriginatorKeyFile="$(keyFile.secureFilePath)"`
4. When packaging the main project add an Additional build property:  `Platform=AnyCPU`
5. Publish to your private nuget repository
