### ISSUE TITLE
Gif images are not rendering in Penchkin PDF generator

### ISSUE THREAD

**Issue by srihari2106** [tuespetre/TuesPechkin#115]
Hi

I am using Pechkin PDF generator, for that i am setting header content and that content is having image tag with .gif formate source. when i try to render the header content the image with .gif formate was not rendering. can u please help me out of this how to render .gif images in pdf using Pechkin pdf generator. Since it was already in use i was unable to migrate to TuesPechkin. I want to use only Pechkin generator.

**Comment by tuespetre** [comment]
Hi; a ten second read on the Google webs indicates that GIFs are not supported by wkhtmltopdf. Sorry!

**Comment by ashkulz** [comment]
@tuespetre: I don't think that's applicable for recent versions; please open an issue if that is the case.

**Comment by tuespetre** [comment]
Thanks Ashish, perhaps I can get around to releasing an update then.
- Derek Gray
