### ISSUE TITLE
How I can use PdfToolset and ImageToolset together?

### ISSUE THREAD

**Issue by bernex** [tuespetre/TuesPechkin#116]
I did:

```
protected readonly static IConverter Converter = new StandardConverter(new PdfToolset(new StaticDeployment(AppDomain.CurrentDomain.BaseDirectory + "/libs/")));
protected readonly static IConverter ConverterImage = new StandardConverter(new ImageToolset(new StaticDeployment(AppDomain.CurrentDomain.BaseDirectory + "/libs/"))); 
```

But I can't use both toolsets.

Thanks!

**Comment by tuespetre** [comment]
I'm afraid you can't in the same process at the moment. [See issue #63 for some related details.](https://github.com/tuespetre/TuesPechkin/issues/63) 

At this time I am busy with other projects; my best recommendation for those needing to process multiple types of conversions, or large volumes of conversions, is to utilize some sort of messaging queue and have scaled worker processes handle the conversions. I will probably get back to this project at some time but even then I am not sure I want to add that into the codebase. Sorry!
