### ISSUE TITLE
Supplying HTML to footer/header

### ISSUE THREAD

**Issue by thiagonsiq** [tuespetre/TuesPechkin#13]
Hi, 

I've noticed the oc.Footer.SetHtmlContent(string htmlUri) way of having an HTML footer/header on Pechkin, i'm in the process of trying this out. 

However, is it possible to supply the HTML directly instead of supplying an html file that contains the code?

Thanks

**Comment by bcampardou** [comment]
Hi,

I did it in a different way.

I write a temp file with the html and then give the path as "htmlUrl".

It works perfectly

```
string headerPath = Path.Combine(Path.GetTempPath(), String.Format("{0}.html", Guid.NewGuid()));
System.IO.File.WriteAllText(headerPath, htmlHeader);
var document = new HtmlToPdfDocument
{
    GlobalSettings =
    {
        ProduceOutline = true,
        DocumentTitle = "Test Report",
        PaperSize = PaperKind.A4,
        OutputFormat = TuesPechkin.GlobalSettings.DocumentOutputFormat.PDF,
        Margins =
       {
            All = 1.375,
            Unit = Unit.Centimeters
        }
    },
    Objects = {
        new ObjectSettings
        {
            HtmlText = htmlContent,
            HeaderSettings = new HeaderSettings{ HtmlUrl = headerPath },
            FooterSettings = new FooterSettings{ HtmlUrl = footerPath, RightText = "[page]"},
            CountPages = true,
            ProduceExternalLinks = true
        }
    }
};
```

So it could be added to TuesPechkin.

What do you think about it ?

**Comment by tuespetre** [comment]
That is exactly what I would have done. Glad you got things working

**Comment by tvolge** [comment]
Hi,

is this working?

``` c#
FooterSettings = new FooterSettings{ HtmlUrl = footerPath, RightText = "[page]"}
```

I'm trying to add custom footer with automatic page numbers, but only html content from the temp file is added.

Also, did you have any issues including header via temp html? It's not added in my output PDF. I applied all settings as you did.

Regards, Tadej

**Comment by bcampardou** [comment]
Hi,

You can't use html footer and the wkhtmltopdf one.

You can add the page number with css.

Regards

**Comment by tvolge** [comment]
@BaobabCoder thank you for explanation. I tought it could be done this way because you put it in your example.

**Comment by bcampardou** [comment]
I'm sorry about that it's a mistake

**Comment by tvolge** [comment]
@BaobabCoder can you please give an example how to add page number with css? Everything what I tried doesn't work. I tried following:

``` css
#pageFooter:after {
    counter-increment: page;
    content: counter(page);
}
```

``` css
@page {
  @top-center {    
    content: counter(page);
  }
}
```

In first attempt page number were added, but they were all '1', in second attempt nothing happened.

I was trying with inline styles for page content and footer.
