### ISSUE TITLE
convert HTML to images too

### ISSUE THREAD

**Issue by hybra** [tuespetre/TuesPechkin#36]
Feature request: to convert not only to pdf, but also to png, jpg, etc. as in wkhtmltoimage

**Comment by tuespetre** [comment]
Still interested in this?

**Comment by alin-prisecaru** [comment]
Could be something useful. If it's easy to make ok. It's up to you as far as I'm concerned. My technique until now was to create a pdf with only 1 page and then use Aspose PDF to get a thumbnail of a page from the PDF file. That way I created HTML screenshots. And they were perfect.
