### ISSUE TITLE
Blank pages!

### ISSUE THREAD

**Issue by neil-119** [tuespetre/TuesPechkin#40]
I tried a simple collection like below:

Objects = {
    new ObjectSettings { HtmlText = "Hello, world!" },
    new ObjectSettings { HtmlText = "Hello, world 3!" },
    new ObjectSettings { PageUrl = "www.google.com" },
    new ObjectSettings { PageUrl = "www.bing.com" },
    new ObjectSettings { HtmlText = "Hello, world 2!" },
}

The objects with PageUrl load fine, but for HtmlText, only the last object ("Hello, world 2!") displays, and all other HtmlText pages are blank.

**Comment by ashkulz** [comment]
The [underlying issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1790) in wkhtmltopdf has been fixed, should be included in a newer release.
