### ISSUE TITLE
Support for the --post argument?

### ISSUE THREAD

**Issue by robinbetts** [tuespetre/TuesPechkin#43]
Hi, is there any plan to support the --post argument allowing additional post data to be sent with the webpage request?  If not, could you give me any pointers as to how I could approach it?  I've had a brief look, but haven't made much progress.
Thanks!

**Comment by ashkulz** [comment]
This whould be fixed for the `0.12.2` release, which should happen in a week.

**Comment by tuespetre** [comment]
Working on this now, have an impediment:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2137

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.

**Comment by tuespetre** [comment]
Bundled 0.12.2.1 has been released on NuGet.
