### ISSUE TITLE
Support for the arguments --cookie, --custom-header, --custom-header-propagation?

### ISSUE THREAD

**Issue by paulashton** [tuespetre/TuesPechkin#45]
So far as I can see, TuesPechkin currently does not expose the following arguments: --cookie, --custom-header, --custom-header-propagation. Are there any plans to do so?

**Comment by ashkulz** [comment]
This would be fixed for the `0.12.2` release, which should happen in a week.

**Comment by wladiston** [comment]
@tuespetre is there a reason because why dont work in your branch master or dev?

**Comment by tuespetre** [comment]
I'm sorry; I don't understand the question. I can tell you some things though:

- The code for this feature should be good in develop and pushed up to GitHub currently
- I have not currently pushed the embedded copies of 0.12.2 to develop, but those commits exist on my local machine
- I was planning to push and release everything Sunday night but I have been sick, so I will try to do that tonight, finally

**Comment by wladiston** [comment]
hahaha I typed faster than I thought. 
I tried to download your dev branch and use this website(http://request.urih.com/) to check the headers and I saw that it's not working yet.
I'll wait yout push. :)

**Comment by ashkulz** [comment]
I'd recommend that you include `0.12.2.1` DLLs which has been released a few days ago. Make sure you document the dependency on VS2013 Runtime, though (or bundle the MinGW DLLs also).

**Comment by tuespetre** [comment]
I did go with 0.12.2.1 for the release. Now, will users have to have the VC++ runtime installed? I may have taken that for granted, as I'm sure all of the machines I've worked on/deployed to have that installed already. 

I may just start bundling the MingW versions from here on out if that is the case (thankfully I worked 2.0.0 to be able to support that!)

**Comment by chrisNom** [comment]
I cannot see clearly if this issue was implemented in the release 0.12.4.1 or some other release. 
What I did realize it that the cookie set procedure for the HtmlToPdfDocument (as shown in  TuesPechkin/TuesPechkin.TestWebApp/Controllers/HomeController.cs ) does not work for me.

So is it not yet implemented?
