### ISSUE TITLE
AccessViolationException while converting multiple pages

### ISSUE THREAD

**Issue by khayhurst** [tuespetre/TuesPechkin#48]
Using the following code:

```
        var document = new HtmlToPdfDocument
        {
            GlobalSettings =
            {
                ProduceOutline = true,
                DocumentTitle = "Pretty Pages",
                PaperSize = PaperKind.A4, // Implicit conversion to PechkinPaperSize
                Margins =
                {
                    All = 1.375,
                    Unit = Unit.Centimeters
                }

            },
            Objects = {
                new ObjectSettings { PageUrl = "http://microsoft.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "https://news.ycombinator.com/"},
                new ObjectSettings { PageUrl = "http://yahoo.ca/"},
                new ObjectSettings { PageUrl = "http://msn.ca/"},
                new ObjectSettings { PageUrl = "http://live.ca/"},
                new ObjectSettings { PageUrl = "http://infoq.com/"},
                new ObjectSettings { PageUrl = "http://slashdot.org/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"},
                new ObjectSettings { PageUrl = "http://google.ca/"}
            }
        };

        var converter = Factory.Create();

        var result = converter.Convert(document);
        var timestamp = DateTime.Now.ToString("hhmmss");
        var filename = String.Format("/{0}.pdf", "PrintedPDF" + timestamp);
        var path = this.Server.MapPath(filename);

        System.IO.File.WriteAllBytes(path, result);

        return File(filename, "application/pdf", Server.UrlEncode(filename));
```

This results in the following exception:

[AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.]
   TuesPechkin.SynchronizedDispatcher.Invoke(Func`1 delegate) +218
   TuesPechkin.Proxy.Convert(HtmlToPdfDocument document) +76

Anyone else have this issue?

**Comment by crush83** [comment]
I'm getting this as well. First I got it with the x86 package. When that failed, I tried the x64 package. I got the BadImageFormatException #80 

So, I cloned the develop repo, recompiled the x64 package for AnyCPU, and used this in my project.

Now I'm back to get this AccessViolationException when trying to call Convert on the converter.

My code is rather simple:

```
        var document = new HtmlToPdfDocument();
        document.GlobalSettings.ProduceOutline = true;
        document.GlobalSettings.PaperSize = PaperKind.Letter;
        document.GlobalSettings.Margins.All = 0.5;
        document.GlobalSettings.Margins.Unit = Unit.Inches;

        var converter = new StandardConverter(
            new RemotingToolset<PdfToolset>(
                new Win64EmbeddedDeployment(
                    new TempFolderDeployment())));

        var stream = new MemoryStream();
        var bytes = converter.Convert(document);
        stream.Write(bytes, 0, bytes.Length);
        stream.Position = 0;
        return stream;
```

The exception is thrown on the Convert line.

**Comment by tuespetre** [comment]
Please open a new issue for yourself next time, it can get weird when re-tracking on an old one, it doesn't show up in the open list and I'm not wanting to re-open it, plus now the OP will be getting these messages when it was like 7 months old.
- Using StandardConverter with RemotingToolset is unnecessary, just use the normal PdfToolset with StandardConverter
- What exactly are you converting? Running a conversion on a document that has no objects specified, or objects without contents/pages to convert, is undefined and I should probably throw in error in those cases

**Comment by crush83** [comment]
Sorry, I haven't used GitHub much in public spaces - mainly only for private work or for personal projects. I don't know all the etiquette yet. I apologize to the original owner and to you. I just wanted to put my message in what I thought was an existing, on-topic space.

This issue is resolved now for me. It was a stupid mistake on my part. Besides not sending any objects to be converted, my problem was that I assumed that AnyCPU would run in 64-bit on my 64-bit Windows installation when in Debug mode. However, I neglected the fact that VS2013 is running in 32-bit mode. Thus, I was trying to access the 64-bit DLL file from a 32-bit application, despite having compiled for AnyCPU.

I'm now trying to create a wrapper for AnyCPU as you suggested in another issue. I won't dirty this thread with my issues with that. I will move back to the thread discussing AnyCPU.

Sorry again.
