### ISSUE TITLE
File System IO Issue?

### ISSUE THREAD

**Issue by timdooling** [tuespetre/TuesPechkin#55]
I have been working with the latest version of this interface and am very pleased with the results!!!!!

However, I have been having one problem with generating output.

The output file is fine, but if I run the program a second time too soon after the first, the program accessing the pdf generator hangs, and no output results.

I am wondering if the output file system.IO interface is being completely closed and disposed.  The hanging appears when I invoke the converter, so I believe it is an internal problem to the interface.

Any thoughts?

timothydooling@gmail.com

**Comment by timdooling** [comment]
I am going to try wrapping the web service calls in a using block and see if that solves the problem.

**Comment by tuespetre** [comment]
I don't think that will do what you think it will do. You should be creating the thread safe converter one time and storing it in a static field or passing around the single instance of it. Are you doing that?

**Comment by timdooling** [comment]
I can try to use a static field for the converter since it seems to behave as though it is static.  I am using the thread safe converter as the code snippet from Wednesday shows.  The problem is that the coding is locking the wrapped file in place and leaving it there after my application that uses the web service containing the pdf converter code terminates.

The file I/O system eventually releases the wkhtmltox file, but that doesn't work well in a production environment.  It doesn't matter which way I attempt to use the code, it still does this.

**Comment by tuespetre** [comment]
Yes, you need to use a single, static instance. That is covered in the readme.

- Derek Gray
