### ISSUE TITLE
64-bit in web app?

### ISSUE THREAD

**Issue by shekky** [tuespetre/TuesPechkin#59]
I cannot get the 64-bit version working in a web app. I always get a BadImageFormatException. Is it possible to use the 64-bit version in a web app or just the 32-bit version?

**Comment by tuespetre** [comment]
If you are targeting 64-bit and using Visual Studio with IIS express, you will want to ensure that your Visual Studio instance is using 64-bit IIS express, by going to Tools - Options - Projects - Web. Please let me know if that's not the case.

- Derek Gray

**Comment by shekky** [comment]
That did the trick. Thanks.

**Comment by tuespetre** [comment]
You're welcome. I know it might be an inconvenience for some but making the 32/64-bit difference explicit was necessary to avoid wasting memory.
