### ISSUE TITLE
PrintMediaType = true NOT working (v.2.0.1)

### ISSUE THREAD

**Issue by wc-matteo** [tuespetre/TuesPechkin#60]
Setting PrintMediaType to true doesn't render css rules targeted for print. It was working before the update (1.something -> 2.0.1). Obviously the css hasn't changed (and cheking with chrome developer tools result in the correct styles being applied).

As a side note, UserStyleSheet got fixed (or implemented :)

**Comment by tuespetre** [comment]
I apologize for this one; it has been addressed by https://github.com/tuespetre/TuesPechkin/pull/58 and an update will be released this weekend.

**Comment by tuespetre** [comment]
This has been published with 2.1.0.
