### ISSUE TITLE
2.0.1 still hanging

### ISSUE THREAD

**Issue by Benjathing** [tuespetre/TuesPechkin#62]
I am having similar problems to the IIS hanging issue in version 2.0.1 in IIS 8.5 (Windows Server 2012 R2.)

Conversion happens without issue on the first instance; however all subsequent instances hang indefinitely.

This problem also persists even in Debug mode on VS2015.
I have attempted to encapsulate the conversion in a mutex; however this has not resolved the problem.

Examining the logs show that the converter hangs just after writing:
**pechkin:default Information: 0 : T: Conversion Progress Changed: (10) 10%**
on the second, and subsequent, conversions.
The logs are showing that the converter *is* being released after each successful conversion.

I can't quite wrap my head around this.

**Comment by tuespetre** [comment]
Are you using a single, statically held instance of the thread safe converter with the remoting toolset? Each of these three criteria must be met for IIS use.

**Comment by Benjathing** [comment]
I do apologise! I thought I had, however on closer inspection I was using the StandardCoonverter. 
Problem is now resolved!
