### ISSUE TITLE
2.1.1 does not load images

### ISSUE THREAD

**Issue by timdooling** [tuespetre/TuesPechkin#64]
I recently upgraded to the latest version, 2.1.1, and the result is that it does not load images anymore.

I reverted to 2.0.1.  It works fine for my needs.

**Comment by tuespetre** [comment]
I've spin up a separate web project (in its own solution) to better separate it from any quirks of being in the same solution as the TuesPechkin projects. I then have TuesPechkin 2.1.1 and TuesPechkin.Wkhtmltox.Win32 0.12.2.1. I just created an empty web project and added a Default.aspx page, modifying the code-behind to look like so:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using TuesPechkin;

namespace TuesPechkinTest
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        static IConverter converter =
            new ThreadSafeConverter(
                new RemotingToolset<PdfToolset>(
                    new Win64EmbeddedDeployment(
                        new TempFolderDeployment())));

        protected void Page_Load(object sender, EventArgs e)
        {
            var result = converter.Convert(new HtmlToPdfDocument { Objects = { new ObjectSettings { PageUrl = "www.google.com" } } });

            Response.Clear();
            Response.ClearHeaders();
            Response.ClearContent();
            Response.AddHeader("Content-Disposition", "attachment; filename=test.pdf");
            Response.AddHeader("Content-Length", result.Length.ToString());
            Response.ContentType = "text/plain";
            Response.Flush();

            new MemoryStream(result).CopyTo(Response.OutputStream);

            Response.End();
        }
    }
}
```

The net result is a pdf of Google's page with the logo image and all. Please double-check that you're not setting any settings like `LoadImages = false` on the WebSettings object. 2.1.0 fixed an issue with setting boolean values where they were not taking effect.

**Comment by timdooling** [comment]
I am actually using the url version of the code.

The code I use is:

```
               Dim document As New TuesPechkin.HtmlToPdfDocument() With { _
               .GlobalSettings = New GlobalSettings() With {.Orientation =  
               GlobalSettings.PaperOrientation.Landscape, _
               .OutputFormat = GlobalSettings.DocumentOutputFormat.PDF, _
               .ProduceOutline = True, .Copies = 1, _
               .DocumentTitle = "Print ACQ", _
                .PaperSize = PaperKind.Letter, _
                .Collate = False, _
               .DPI = 300, _
               .Margins = New MarginSettings(0.5, 0.5, 0.5, 0.5) With {.Unit = TuesPechkin.Unit.Inches}
               } _
               }
               document.Objects.Add(New ObjectSettings() With {.PageUrl = pageurl, _
                                                                .WebSettings = New WebSettings() With {.LoadImages = True, _
                                                                .PrintBackground = False, _
                                                                .EnableJavascript = True}})

                document.GetObjects()
```

I have LoadImages set to true.  The PageUrl is set to a page in my web service that creates the html that I want to convert.

I upgraded and the same code failed to load the images.

Upgrading the package was the only change.

**Comment by tuespetre** [comment]
Interesting. How are the images specified in the HTML? Are they `<img>` elements or are you using something like `background-image: url(...)` somewhere in CSS?

**Comment by timdooling** [comment]
style="background-image:url('Logo.png'); width:327px;height:80px; display: block; background-repeat: no-repeat;"  in a div (I couldn't put the actually div code in my comment).

That is actually what I am using.  It worked fine before the upgrade.  I have had varying results with .css files, so I am currently specifying the css mostly inline.  However, the converter does appear to pickup some css from my css file.

Some of my issues with the css may have been with the sharepoint site my app is working in.  It loads a css file after my main one which appears to reset much of my formatting.  This is one reason I went with the web service print routine sent in as a url because I am printing from two different types of sites:  the sharepoint site and a standalone program for another type of user.  I tried working with the render method initially, but it didn't seem to be rendering the css file.  Now I know a little more than I did, and I think the issue was in the sharepoint site.

**Comment by tuespetre** [comment]
Alright; before the upgrade the `.PrintBackground = False, _` would not have worked properly. Since 2.1.0 (and 2.1.1) fix the issue with boolean settings, it is now working properly for you, and since your image is a css background, it will not print.

**Comment by timdooling** [comment]
Okay.  That makes sense.

I thought that referred to a general body background on a page when I saw the issue.

I can change that in my code without any problems.
