### ISSUE TITLE
OLE Error when using TuesPechkin.Wkhtmltox.Win64

### ISSUE THREAD

**Issue by talberti** [tuespetre/TuesPechkin#66]
TuesPechkin ver. 2.1.1 
TuesPechkin.Wkhtmltox.Win64 0.12.2.1

```
        IConverter converter =
        new StandardConverter(
            new PdfToolset(
                new Win64EmbeddedDeployment(
                    new TempFolderDeployment())));

        byte[] result = converter.Convert(document1);
```

When I use the above code in a console application set to x64 as a Platform Target I get the following error:

Qt: Could not initialize OLE <error 80010106>

Any Ideas?

**Comment by tuespetre** [comment]
This is an old/known issue when running in console. It stems from somewhere in wkhtmltopdf since it uses Qt under its hood. Nothing we can do about it from the .NET level. :(
