### ISSUE TITLE
I want to Export Windows Authenticated Urls to PDF by using TuesPechkin, can someone help me 

### ISSUE THREAD

**Issue by raviit36** [tuespetre/TuesPechkin#68]

**Comment by tuespetre** [comment]
LoadSettings has username and password properties for this:

https://github.com/tuespetre/TuesPechkin/blob/develop/TuesPechkin/Document/LoadSettings.cs

Let me know if that works for you!

**Comment by raviit36** [comment]
Hi tuespetre,
Thanks for your reply , I am using it in a Website, which is using Pechkin, can you tell me , how to use this Loadsettings along with Pechkin dll

byte[] buffer = new Pechkin.Synchronized.SynchronizedPechkin(
                     new Pechkin.GlobalConfig( )).Convert(
                        new Pechkin.ObjectConfig()
                        .SetLoadImages(true)
                        .SetAllowLocalContent(true)
                        .SetScreenMediaType(true)
                        .SetCreateExternalLinks(true)
                        .SetPageUri(uriString)
                        .SetPrintBackground(true)
                        .SetRunJavascript(true)

```
                    );
```

Thanks
