### ISSUE TITLE
A3 document to A4

### ISSUE THREAD

**Issue by RobiGoBH** [tuespetre/TuesPechkin#72]
Hi, I have a problem, with some pages rendering, they don't fit on a A4 page, and when I try to render in a A4 page, I got a lot of half or blank pages... and then I had the idea, what happens if I render that html on a A3 page, then I resize the A3 document to A4, and save the A4 version...

It has a possibility to do it somehow?

Thank you! :)

**Comment by tuespetre** [comment]
I'm sorry to close your issue again now that it's on the right repo but after thinking about it, your issue is better suited for wkhtmltopdf's repo instead since it is just a matter of how to configure your conversion with it.
