### ISSUE TITLE
To pass an HTML string

### ISSUE THREAD

**Issue by DKanarsky** [tuespetre/TuesPechkin#73]
Hello! I use TuesPechkin to convert html into svg format. And i faced the fact that there is no way to pass an html string only a file name or web page url. On the other hand it's quite possible if converting to pdf just setting HtmlText property of ObjectSettings instance. 
It's not good for me to create file and then pass it to convert function. Is there any other way to fix this problem?
Thank you!

**Comment by tuespetre** [comment]
Sorry, but it seems wkhtmltopdf only allows the url or file path for conversion to image. You could just create a temp file and delete it right away using Path.GetTempFileName, or you could hold the contents in session and create a MVC controller action or something like an ashx handler to let wkhtmltopdf access the contents via a temporary url (probably just using the session key.)
