### ISSUE TITLE
A3 document to A4

### ISSUE THREAD

**Issue by RobiGoBH** [tuespetre/TuesPechkin#74]
Ok, It is your project, with your rules, but I have no idea who else I can ask about, because you are the developer, and this thing is not documented, (or if it is, please give me a link to that documentation...), and yes, it is possible this question sort much better in wkhtmltopdf's repo, but I use TuesPechkin in my project, not wkhtmltopd... and I don't want to disturb you so much with this, because I have solved yet, I generate the pdf with TuesPechkin, then I open the saved file, and I resize with iTextSharp (*because I have found a good example for resizing with iTextSharp),,, but I want to solve this problem using with only one pdf library, and your library is do his job very well, so if it possible to resize with it, please give me a documentation or an example please...  

Thank you!

**Comment by tuespetre** [comment]
Again I apologize; this project is just a .NET wrapper around wkhtmltopdf:

https://github.com/wkhtmltopdf/wkhtmltopdf

As far as documentation, you are right in that I am missing some documentation related to which object properties match to which wkhtmltopdf settings, for the most part they are fairly straightforward though.

I am just unsure of what wkhtmltopdf settings need to be set to accomplish what you are needing, so I would say ask them and then if you have trouble setting those settings with my library, I can offer further help in that regard.

**Comment by RobiGoBH** [comment]
Thank you so much! :)
