### ISSUE TITLE
Images are blank via IIS with V1.0.3

### ISSUE THREAD

**Issue by ghost** [tuespetre/TuesPechkin#75]
Hi there,

We are in the final stages of testing before a release, and as such we are hoping to avoid upgrading the TuesPechkin package this late in our dev cycle. We are currently using version 1.0.3, but we have encountered an issue. We have been using TuesPechkin to convert the contents of an on screen word editor(html) to a pdf export, we have recently added the ability to insert images into the text editor, these are stored in our database. When we are about to convert this to a pdf we process the images by saving them into a temporary file and replace the <img> tags "src" field with a link to the temporary file. During development this worked without issue using IIS Express, however we have since deployed this to our testing production server using full IIS and there are no images being produced in the converted PDF file. 

We have even tried with hard coded <img> src tags to permanently accessible images with no joy.

If you could give me any pointers or info as to where we are going wrong or if this is a known issue then that would be great. If you need any info on our code or set up then let me know.

Here is our test code which produces the PDF without the image:

```
protected void GenerateTest_Click(object sender, EventArgs e)
    {
        string documentString = "​< \img  style=\"width: 347px; height: 358px;\" src= URL of Image on the Server /><br />Bottom of Page\";


        // Convert HTML to PDF
        byte[] pdf = ConvertToPDF(documentString);


        //Return the PDF file
        Response.Clear();
        Response.ClearContent();
        Response.ClearHeaders();
        Response.ContentType = "application/pdf";
        Response.AddHeader("Content-Disposition", string.Format("attachment;filename=Procedure - {1}.pdf; size={0}", pdf.Length, "Test"));
        Response.BinaryWrite(pdf);
        Response.Flush();
        Response.End();
    }
```

and our convert to PDF Method:

```
private byte[] ConvertToPDF(string html)
    {
        //Set up the settings for PDF document
        var webSettings = new TuesPechkin.WebSettings();
        webSettings.LoadImages = true;
        webSettings.PrintMediaType = true;
        webSettings.PrintBackground = true;
        webSettings.EnableIntelligentShrinking = true;

        var objSettings = new ObjectSettings();
        objSettings.WebSettings = webSettings;
        objSettings.HtmlText = html; // Sets the Procedure HTML as the content of the PDF
        objSettings.ProduceExternalLinks = true;
        objSettings.LoadSettings.ZoomFactor = 1.45; //this setting closely matches the print preview of editor content in browsers.

        var globalSettings = new GlobalSettings();

        globalSettings.PaperSize = PaperKind.A4;
        globalSettings.Margins.Unit = TuesPechkin.Unit.Inches;
        globalSettings.Margins.Top = 0.3;
        globalSettings.Margins.Bottom = 0.25;
        globalSettings.Margins.Left = 0.35;
        globalSettings.Margins.Right = 0.35;
        globalSettings.ImageDPI = 96;         
        globalSettings.PageOffset = 0;

        var pechkin = Factory.Create();

        var document = new HtmlToPdfDocument() { Objects = { objSettings } };
        document.GlobalSettings = globalSettings;
        // Convert to PDF and return the byte [] of the PDF
        return pechkin.Convert(document);
    }
```

**Comment by tuespetre** [comment]
You might verify where the temporary files are being created and verify that on the staging server, the app pool identity has sufficient access. In the synchronized thread (for versions prior to 2.x.x, and within the ThreadSafeConverter for versions >= 2.x.x), the thread's principal is reverted back to the process identity which will be the app pool identity for IIS applications.

**Comment by timdooling** [comment]
The images are likely not being found on the development server by the application.

Use logging and error-trapping to find out where the files are actually being located.  I have found using my server setup that the Url I believe I am at on the server is not where I am actually at, and programmatically returning url information sometimes does not yield the correct offset.

The actual Url you need to use may have an additional branch in it.

You may be expecting and the asp.net coding may return {Url}/, but you are really at {Url}/{SURPRISE}/ because of the particular setup of your server.

It works differently on localhost than it does on a remote server.  I have to code my programs so that they differentiate between localhost and the remote server as far as the offsets are concerned.

**Comment by tuespetre** [comment]
@tocherrocks haven't heard back so assuming you figured it out. Let me know otherwise

**Comment by chyshu** [comment]
Hi, there

I'm tried to use the convert a HTML to jpg images in Windows 8 with VS2010 , but I got a problem is the output image have 512000*800 pixels, what parameters I should setup?

my code :
            var Doc = new HtmlToImageDocument()
            {
      
                In = url,
                Format = "jpg",
                ScreenWidth =800,
                ScreenHeight = 800,
 
            };
            
            
             byte[]  buffer =  converter.Convert(Doc);

             StreamWriter sw = new StreamWriter("d:\\test1.jpg");
             BinaryWriter bw = new BinaryWriter(sw.BaseStream);
             bw.Write(buffer);
             bw.Close();
