### ISSUE TITLE
Deadlock v2.1.1

### ISSUE THREAD

**Issue by Lockyc** [tuespetre/TuesPechkin#76]
Hello,

I have been trying to use TuesPechkin in a SharePoint event listener.
Unrelated to the deadlock i had issues including the TuesPechkin solutions with my solution it was giving me compile errors about different architectures i ended up having to compile the projects separately and just include the DLL. I needed to compile so I could sign the projects.

The first pdf conversion would work well, but when i started a second pdf conversion tuespechkin would hang on "Monitor.Wait(task);" line 47 in ThreadSafeConverter.cs.

Looking around it seemed that "StopThread()" or ToolSet Unloaded were never called. I dont know if this is by design, but i rearranged how i called the converter to specifically call Unload on the toolset and it has fixed the deadlock issue.
Example:

```
RemotingToolset<PdfToolset> toolset = 
        new RemotingToolset<PdfToolset>(
            new Win64EmbeddedDeployment(
                new TempFolderDeployment()))
IConverter converter = new ThreadSafeConverter(toolset);

byte[] result = converter.convert(document);

toolset.Unload();
```

**Comment by tuespetre** [comment]
Hello,

As noted in the readme, for IIS/multithreaded use you will want to instantiate a single converter/toolset/deployment combination and store it in a static field (or DI container if that's your thing)

**Comment by Lockyc** [comment]
Ah, so sorry about that
