### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by divyashreeup** [tuespetre/TuesPechkin#84]
This is not an issue, but is there any step by step guide as to how to use TuesPechkin, similar to this one?

https://codeutil.wordpress.com/2013/09/16/convert-html-to-pdf/

I would like to know which DLL references to be added, which DLLs should be added to the root folder and stuff like that.

I am trying to convert html text to pdf.

**Comment by tuespetre** [comment]
There is:

https://github.com/tuespetre/TuesPechkin#5-putting-it-all-together

Add the NuGet packages (minding your 32 vs. 64 bit needs) and see those examples.
