### ISSUE TITLE
Factory. Create -  Factory does not exist

### ISSUE THREAD

**Issue by limayesn** [tuespetre/TuesPechkin#91]
Hi,
I am using Tuespechkin, however i am getting error "Factory does not exist" on below line:
var pechkin = Factory.Create(new GlobalConfig());

I have already used "Pechkin.Synchronized" successfully to convert html to pdf.
I switched to "TuesPechkin" because i faced same issue given in http://www.tagwith.com/question_1013921_pechkin-and-in-used-process-in-iis

Can you let me know if i m missing any dlls?

Thanks
limayesn

**Comment by bcampardou** [comment]
Hi,

If my understanding is good, there is no factory in the last version (see issue 'Create a TuesPechkin.BlackBox package #88')

Béranger

**Comment by limayesn** [comment]
Hi, 
  I had referenced link https://github.com/tuespetre/TuesPechkin/issues/5
  for my code. Wanted to dispose pechkin object after conversion as suggested in that link.

I m already using pechkin.synchronized, hence wanted to know if i could tweak code to dispose object. Below is my code:

byte[] html = File.ReadAllBytes(path);

```
            byte[] pdf = null;                

            Pechkin.GlobalConfig pechkinGlobalConfig = new Pechkin.GlobalConfig().SetMargins(10, 10, 10, 10).SetPaperSize(PaperKind.A4);
            Pechkin.ObjectConfig pechkinObjConfig = new Pechkin.ObjectConfig()
                               .SetLoadImages(true)
                               .SetPrintBackground(true)
                               .SetScreenMediaType(true)
                               .SetZoomFactor(1.5)
                               .SetCreateExternalLinks(true);


            Pechkin.Synchronized.SynchronizedPechkin pch = new Pechkin.Synchronized.SynchronizedPechkin(pechkinGlobalConfig);

            pdf = pch.Convert(pechkinObjConfig, html);
```

Now it seems i will need to use Iconverter for conversion, is that correct?

Thanks
limayesn

**Comment by limayesn** [comment]
Hi,
  Should i use any lower version of TuesPechkin (like v1.0.3 or any other) which contains version shown in https://github.com/tuespetre/TuesPechkin/issues/5
to get disposable object of pechkin?

Thanks
limayesn

**Comment by bcampardou** [comment]
Yes that's correct. This is the way I use my converter :

```
    private static IConverter converter =
        new ThreadSafeConverter(
            new RemotingToolset<PdfToolset>(
                new Win32EmbeddedDeployment(
                    new TempFolderDeployment())));
```

Do you think there is a need TuesPechkin should be disposed ?

Béranger

**Comment by limayesn** [comment]
Thanks for the response. Yes, thats the way i will need to do it. No, i don't think it needs to be disposed because above converter takes care of that (which is there in latest version).

Its an amazing library for html to pdf conversions (kudos to the authors). Actually, I had already used synchronized pechkin in the code and deployed on server. On server, facing issue of hanging while conversion (needed to kill w3wp process to get it working).

I will try to use IConverter, however it would be great if i could get hold of the TuesPechkin version mentioned in https://github.com/gmanny/Pechkin/pull/42

Thanks
limayesn

**Comment by tuespetre** [comment]
Sorry, I will close this issue as it pertains to usage only. And you do not want to dispose the converter, as you are supposed to hold a reference to the single instance through the whole application lifecycle.
