### ISSUE TITLE
Custom Paper Size

### ISSUE THREAD

**Issue by NeilMeredith** [tuespetre/TuesPechkin#92]
Is there a way to set a custom paper size?  For example, how could I set a 3 inch by 4 inch paper size?

**Comment by tuespetre** [comment]
There is:

https://github.com/tuespetre/TuesPechkin/blob/develop/TuesPechkin/Document/PechkinPaperSize.cs

The example you see in the README file just shows that the `PaperKind` has an implicit conversion to `PechkinPaperSize`.
