### ISSUE TITLE
Send html as a string instead by url to HeaderSettings

### ISSUE THREAD

**Issue by ivanjordan** [tuespetre/TuesPechkin#94]
Is there the possibility to send HTML as string instead to send the url on HeaderSettings?

**Comment by bcampardou** [comment]
Hi,

You can look at this issue https://github.com/tuespetre/TuesPechkin/issues/13#issuecomment-78048697

```
string headerPath = Path.Combine(Path.GetTempPath(), String.Format("{0}.html", Guid.NewGuid()));
System.IO.File.WriteAllText(headerPath, htmlHeader);
var document = new HtmlToPdfDocument
{
    GlobalSettings =
    {
        ProduceOutline = true,
        DocumentTitle = "Test Report",
        PaperSize = PaperKind.A4,
        OutputFormat = TuesPechkin.GlobalSettings.DocumentOutputFormat.PDF,
        Margins =
       {
            All = 1.375,
            Unit = Unit.Centimeters
        }
    },
    Objects = {
        new ObjectSettings
        {
            HtmlText = htmlContent,
            HeaderSettings = new HeaderSettings{ HtmlUrl = headerPath },
            FooterSettings = new FooterSettings{ HtmlUrl = footerPath, RightText = "[page]"},
            CountPages = true,
            ProduceExternalLinks = true
        }
    }
};
```

Béranger

**Comment by ivanjordan** [comment]
Thank you :), I will apply.

Regards

De: Béranger [mailto:notifications@github.com] 
Enviado el: jueves, 26 de marzo de 2015 11:40
Para: tuespetre/TuesPechkin
CC: Ivan Jordan
Asunto: Re: [TuesPechkin] Send html as a string instead by url to HeaderSettings (#94)

Hi,

You can look at this issue #13 (comment) https://github.com/tuespetre/TuesPechkin/issues/13#issuecomment-78048697 

string headerPath = Path.Combine(Path.GetTempPath(), String.Format("{0}.html", Guid.NewGuid()));
System.IO.File.WriteAllText(headerPath, htmlHeader);
var document = new HtmlToPdfDocument
{
    GlobalSettings =
    {
        ProduceOutline = true,
        DocumentTitle = "Test Report",
        PaperSize = PaperKind.A4,
        OutputFormat = TuesPechkin.GlobalSettings.DocumentOutputFormat.PDF,
        Margins =
       {
            All = 1.375,
            Unit = Unit.Centimeters
        }
    },
    Objects = {
        new ObjectSettings
        {
            HtmlText = htmlContent,
            HeaderSettings = new HeaderSettings{ HtmlUrl = headerPath },
            FooterSettings = new FooterSettings{ HtmlUrl = footerPath, RightText = "[page]"},
            CountPages = true,
            ProduceExternalLinks = true
        }
    }
};

Béranger

**Comment by tuespetre** [comment]
Thanks @BaobabYeah
