### ISSUE TITLE
TuesPechkin does not compile with .NET 4.5.2

### ISSUE THREAD

**Issue by ghost** [tuespetre/TuesPechkin#96]
Tried to run the TestWebApp example in the repo, it is compiling in .net 4.0 and works. However when I tried to change it to Asp.net MVC 5 and .NET 4.5.2 which my host is running, I get the following error.

NUGET Packages
  <package id="TuesPechkin" version="2.1.1" targetFramework="net45" />
  <package id="TuesPechkin.Wkhtmltox.Win32" version="0.12.2.1" targetFramework="net45" />

CONTROLLER
<pre><code>
    public class HomeController : Controller
    {
        private static IConverter converter = new ThreadSafeConverter(new RemotingToolset<PdfToolset>(new Win32EmbeddedDeployment(new TempFolderDeployment())));

```
    public ActionResult Index()
    {
        var doc = new HtmlToPdfDocument();
        doc.Objects.Add(new ObjectSettings { PageUrl = "www.google.com " });

        for (var i = 0; i < 5; i++)
        {
            var bytesAsPdf = converter.Convert(doc);
            if (bytesAsPdf.Any()) return File(bytesAsPdf, "application/pdf", "Order_Confirmation.pdf");
        }

        return this.View();
    }
}
```

</pre></code>

<pre><code>
Server Error in '/' Application.

Could not load type 'TuesPechkin.TempFolderDeployment' from assembly 'TuesPechkin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Could not load type 'TuesPechkin.TempFolderDeployment' from assembly 'TuesPechkin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
</pre></code>

**Comment by timdooling** [comment]
Where and how is TempFolderDeployment defined?

**Comment by tuespetre** [comment]
I hope/trust that you were able to work something out. Your error says it's targeting version 1.0.0.0 where the current source is at 2.1.1.0. Sounds like a dirty workspace problem

**Comment by ghost** [comment]
Nope, had to target .net 4.0 not 4.5 and then it worked

**Comment by tuespetre** [comment]
I see. I had no problem with 4.5.2 locally. :coffee:

**Comment by ghost** [comment]
Well I did, so went back to using 1.x version, it's working now so I've left it. Close the issue and if someone else has the same issue revisit it, thanks Derek for following up. :)
Date: Wed, 22 Apr 2015 13:11:24 -0700
