### ISSUE TITLE
Special Characteres in the footer are encoded in UTF-8

### ISSUE THREAD

**Issue by Wjat777** [tuespetre/TuesPechkin#98]
Hi,

I'm try print the footer with special characteres (ASCII > 128) and they are encoded . See my test case:

``` c#
        public ActionResult PrintPDF(string query)
        {
            byte[] bytes = null;
            string footer = "";
            for (int i = 128; i <= 250; i++)
            { footer += (char)i;
            if (i % 15==0) footer += "\r\n";
            }
            html = "<html><body>" + footer + "</body></html>";
            var document = new HtmlToPdfDocument
            {
                GlobalSettings =
                {
                    ProduceOutline = true,
                    DocumentTitle = "Fiche Synthèse de l'Usager",
                    PaperSize = PaperKind.Legal, // Implicit conversion to PechkinPaperSize
                    Margins =
                    {
                        Top = 0.15,
                        Left = 0.05,
                        Bottom = 0.25,
                        Right = 0.05,
                        Unit = Unit.Inches
                    }
                },
                Objects = { new ObjectSettings 
                    { HtmlText = html, 
                        WebSettings = new WebSettings { EnableIntelligentShrinking = false,DefaultEncoding="UTF-8" }, 
                        FooterSettings = new FooterSettings { CenterText=footer}

                    } 
                }
            };
            byte[] result = converter.Convert(document);
            return File(result, "application/pdf");
        }
```

the result is:
in the body:
¡¢£¤¥ ¦§¨©ª«¬®¯°±²³´·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïð ñòóôõö÷øùú

in the footer:
ÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂÂ

Thanks

William

**Comment by Wjat777** [comment]
Hi,

I tested with the executable [wkhtmltopdf 0.12.2.1 (with patched qt) ] and I don't have this problem:
C:\Program Files\wkhtmltopdf\bin>wk test.html --encoding "UTF-8" --footer-cente
r "¡¢£¤¥ ¦§¨©ª«¬®¯°±²³´·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîï
ð ñòóôõö÷øùú" c:\temp\test.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

the content of  test.html is

``` HTML
<html>
<body>
¡¢£¤¥ ¦§¨©ª«¬®¯°±²³´·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïð ñòóôõö÷øùú
</body>
</html>
```

The body and footer are rendered correctly.

**Comment by tuespetre** [comment]
Thank you for testing that out in the command line! I'm going to look and see how the command line's 'encoding' argument maps to the lib API and see what's up, maybe there's some kind of discrepancy.

**Comment by kharenikhil** [comment]
Is this issue fixed? I am giving some UTF-8 string to Footer LeftText property and the same is not getting encoded properly. I have choosen "DefaultEncoding=UTF-8" within Web Settings

**Comment by westsajd** [comment]
Same issue here. My test case:

For given config:

```
var document = new HtmlToPdfDocument
            {
                GlobalSettings =
                {
                    ProduceOutline = true,
                    DocumentTitle = "Report",
                    PaperSize = PaperKind.A4 // Implicit conversion to PechkinPaperSize
                },
                Objects =
                {
                    new ObjectSettings {
                        HtmlText = content,
                        WebSettings = new WebSettings
                        {
                            DefaultEncoding = "UTF-8",
                            LoadImages = true,
                            PrintBackground = true
                        },
                        FooterSettings = new FooterSettings
                        {
                            FontSize = 8,
                            RightText = _footer
                        }
                    }
                }
            };
```

when `_footer` is a string with a value of:

> lorem ipsum ąęóćźżłń

Document gets rendered with badly encoded footer:
![wrong_encoding](https://cloud.githubusercontent.com/assets/3727799/9168397/d917b720-3f57-11e5-9600-b9e2ebeedf58.PNG)

**Comment by simpa151** [comment]
Is there any solution to this? I need to support æøå but these chars gets rendered incorrectly. Please help. Thank you in advance.

**Comment by simpa151** [comment]
Well i made it work here is the html i used => example: 

```
`<code> <html lang=da-dk ><head>
    <meta charset=utf-8 /><title></title>
</head>
<body><div><p>This might take a bit to convert!æøå</p></div>

</body>
</html>
`</code>``
```

Hope this can help others...

**Comment by simpa151** [comment]
` @"<html lang="+'"'+ "da-dk" +'"'+ @"><head>
    <meta charset=" + '"'+ "utf-8" + '"' + @"/><title></title>
</head>
<body><div><h1>Pretty Websites</h1><p>This might take a bit to convert!æøå</p></div>
    
</body>
</html>"`

**Comment by Wjat777** [comment]
Hi, 

With [wkhtmltopdf 0.12.3.4](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.4) this issue is fixed. See: #[2885](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2885): enforce UTF-8 encoding for input strings in the API

Thanks
