### ISSUE TITLE
Not converting web page have query string

### ISSUE THREAD

**Issue by ppn123** [tuespetre/TuesPechkin#99]
Hi,

It's not converting web page have query string
Eg:  http://www.google.com/search?q=Kit+Kat+Lounge+&+Supper+Club+Chicago+IL
Please help to solve this issue.

Best Regards
Pradeep.N

**Comment by tuespetre** [comment]
Sorry for the delay in response; I cannot reproduce the issue with 2.1.1. Please update your version / provide sample code if the issue persists.
